from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import xgboost as xgb

from src.ml.features import HtmlFeatures

logger = logging.getLogger("scanner.ml")


class PhishingClassifier:
    def __init__(self, model_path: str):
        self._model = xgb.Booster()
        self._model.load_model(model_path)

        # Log manifest if available (generated by training/train.py)
        manifest_path = Path(model_path).parent / "model-manifest.json"
        try:
            with open(manifest_path) as f:
                manifest = json.load(f)
            logger.info(
                "XGBoost model loaded",
                extra={
                    "model_path": model_path,
                    "model_version": manifest.get("version"),
                    "trained_at": manifest.get("trained_at"),
                    "accuracy": manifest.get("metrics", {}).get("accuracy"),
                    "phishing_samples": manifest.get("training_data", {}).get("phishing_samples"),
                    "neutral_samples": manifest.get("training_data", {}).get("neutral_samples"),
                },
            )
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            logger.info("XGBoost model loaded", extra={"model_path": model_path})

    def predict_score(self, features: HtmlFeatures) -> float:
        vector = np.array([features.to_vector()])
        dmat = xgb.DMatrix(vector)
        score = self._model.predict(dmat)
        return float(score[0])
